[package]
name    = "auth-scope-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "auth-scope-server"
path = "src/main.rs"

[dependencies]
auth-scope-proto = { workspace = true }
auth-scope-ca    = { workspace = true }
tokio            = { workspace = true }
tokio-vsock      = { workspace = true }
rcgen            = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
clap             = { workspace = true }
tracing          = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror        = { workspace = true }
anyhow           = { workspace = true }
